### ISSUE TITLE
TarsGO的测试代码有问题

### ISSUE THREAD

**Issue by defool** [rpcx-ecosystem/rpcx-benchmark#6]
https://github.com/rpcx-ecosystem/rpcx-benchmark/blob/master/tarsgo/client/tarsgo_mclient.go#L64
这里的comm请使用全局变量，否则会退化到短连接方式，对性能影响极大。
期待修改后能看到新的性能数据。

**Comment by smallnest** [comment]
这里每个goroutine模拟一个独立的分布式的客户端，就像部署在独立的一个机器或者进程中， 所以每个client有自己的comm。 
其它lib也是基于这个方式测试的，用以模拟独立的客户端。

如果共享一个comm,就不能真正模拟真正并发的client了。

**Comment by smallnest** [comment]
每个客户端(连接)会持续发送数据，也不是短连接的方式。

https://github.com/rpcx-ecosystem/rpcx-benchmark/blob/master/tarsgo/client/tarsgo_mclient.go#L74

**Comment by defool** [comment]
了解了，我找相关同学排查看看

**Comment by defool** [comment]
这个问题初步判断跟pb有关，之前有人用tars协议+tarsrpc来压测数据跟这里的差比较大

**Comment by defool** [comment]
暂时没人来跟进，先关闭issue吧。

**Comment by lesismal** [comment]
> 这个问题初步判断跟pb有关，之前有人用tars协议+tarsrpc来压测数据跟这里的差比较大

不是pb的问题，各个lib都用的pb

看了下，TarsGO测试代码开启了日志文件，大量的写文件，所以慢了很多，关闭日志文件后，比rpcx没慢太多

**Comment by lesismal** [comment]
> 暂时没人来跟进，先关闭issue吧。

我的破笔记本C/S本机跑，TarsGO比rpcx慢10-20%的范围，但是我机器不太稳定，浏览器视频开着一大堆，没README里的10倍那么夸张，所以我就没搞稳定环境继续看了
跨机器网络开销占比高，TarsGO慢的比例也会更小些
不用谢 :smile::smile::smile:

**Comment by lesismal** [comment]
我的arpc没那么多复杂功能，暂时比你们都快  :grin::grin::grin:

**Comment by smallnest** [comment]
欢迎提交pull request 完善测试代码

**Comment by lesismal** [comment]
OK，PR了
